# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "libxml-ruby", "3.1.0"
gem "couchrest", "2.0.1"
gem "pry"
gem "interactive_editor"
gem "awesome_print"
gem "pry-clipboard"
