version: '3.1'

services:
  couchdb:
    image: couchdb:2.1.2
    ports:
      - 5984:5984
    volumes:
      - couchdbvol:/opt/couchdb/data

  client:
    build: ./client
    command: sleep infinity
    environment:
      - COUCH_ROOT_URL=http://couchdb:5984

volumes:
  couchdbvol:
