version: '3.1'

services:
  redis1:
    image: redis:3.2.8
    sysctls:
      - net.core.somaxconn=512
    ports:
      - 6379:6379
    volumes:
      - redis1:/data

  redis2:
    image: redis:3.2.8
    command: redis-server --slaveof redis1 6379
    sysctls:
      - net.core.somaxconn=512
    ports:
      - 6380:6379
    volumes:
      - redis2:/data


  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis1:6379
    ports:
      - 8081:8081

volumes:
  redis1:
  redis2:

