version: '3.1'

services:
  redis:
    image: redis:3.2.8
    sysctls:
      - net.core.somaxconn=512
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  redis:
